[package]
name = "rust_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tokio = {version = "1", features= ["full"]}
snowflake-connector-rs = "0.6.5"
csv = "1.3.1"
actix-cors = "0.7.0"